spring:
  datasource:
    password: d880a69c64c5d45cf3023ff9b678281ed2d92ab29f4bc56e2f0bc3cf243c49f8
    url: jdbc:postgresql://ec2-34-195-115-225.compute-1.amazonaws.com:5432/dc94udc62q715u
    username: lfanbpllgpwwsg

  jpa:
    hibernate:
      dialect : org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
sme:
  application-folder: C:\Users\Abdel\Desktop\SCOR_SME\scor-sme


jwt:
  secret: javainuse
server:
  port: 5000
